language: go
go: tip
script: go get github.com/gorilla/rpc/json && go test -v ./...
notifications:
  email:
    recipients:
      - streamweaver@gmail.com
    on_success: change
    on_failure: always
    branches:
  only:
    - master
    - develop